export const WEBVIEW_SHOW_PAGE = 'WEBVIEW_SHOW_PAGE'
export const WEBVIEW_HIDE_PAGE = 'WEBVIEW_HIDE_PAGE'
export const WEBVIEW_SHOW_SPINNER = 'WEBVIEW_SHOW_SPINNER'
export const WEBVIEW_HIDE_SPINNER = 'WEBVIEW_HIDE_SPINNER'

export const ORDER_UPDATE = 'ORDER_UPDATE'

export const LOGIN_SET_REQUEST_TOKEN = 'LOGIN_SET_REQUEST_TOKEN'
export const LOGIN_SET_USER_DATA = 'LOGIN_SET_USER_DATA'
export const LOGIN_LOGOUT = 'LOGIN_LOGOUT'

export const FETCH_BOOKMARK_CACHE = 'FETCH_BOOKMARK_CACHE'
export const FETCH_HOTENTRY_REQUEST = 'FETCH_HOTENTRY_REQUEST'
export const FETCH_HOTENTRY_SUCCESS = 'FETCH_HOTENTRY_SUCCESS'
export const FETCH_HOTENTRY_FAILURE = 'FETCH_HOTENTRY_FAILURE'
export const FETCH_MY_BOOKMARK_REQUEST = 'FETCH_MY_BOOKMARK_REQUEST'
export const FETCH_MY_BOOKMARK_SUCCESS = 'FETCH_MY_BOOKMARK_SUCCESS'
export const FETCH_MY_BOOKMARK_FAILURE = 'FETCH_MY_BOOKMARK_FAILURE'
export const FETCH_SEARCH_RESULT_REQUEST = 'FETCH_SEARCH_RESULT_REQUEST'
export const FETCH_SEARCH_RESULT_SUCCESS = 'FETCH_SEARCH_RESULT_SUCCESS'
export const FETCH_SEARCH_RESULT_FAILURE = 'FETCH_SEARCH_RESULT_FAILURE'

export const COMMENT_SHOW = 'COMMENT_SHOW'
export const COMMENT_HIDE = 'COMMENT_HIDE'

export const BOOKMARK_ADD = 'BOOKMARK_ADD'
export const BOOKMARK_CLOSE = 'BOOKMARK_CLOSE'
export const BOOKMARK_SHOW_DATA = 'BOOKMARK_SHOW_DATA'
